export const posts = [
  {
    id: 1, cat: "health", catLabel: "Health Tips",
    title: "Understanding High Blood Pressure: Signs, Risks & Prevention",
    excerpt: "Hypertension is one of the leading causes of stroke and heart disease in Uganda. Learn the warning signs, risk factors, and simple lifestyle changes that can protect your heart.",
    author: "Dr. Katumba Joseph", initials: "KJ", color: "#1a3fa8",
    date: "April 10, 2026", readTime: "6 min", trending: true,
    content: [
      { heading: "What is High Blood Pressure?", body: "High blood pressure (hypertension) occurs when the force of blood against your artery walls is consistently too high. It is often called the 'silent killer' because it usually has no symptoms until serious damage has already occurred. Normal blood pressure is below 120/80 mmHg. Readings consistently above 140/90 mmHg indicate hypertension." },
      { heading: "Warning Signs to Watch For", body: "While hypertension is often symptomless, some people experience severe headaches, shortness of breath, nosebleeds, chest pain, or vision problems. If you experience any of these, seek medical attention immediately. The only reliable way to know your blood pressure is to have it measured regularly." },
      { heading: "Risk Factors", body: "Key risk factors include a family history of hypertension, being overweight or obese, physical inactivity, a diet high in salt, excessive alcohol consumption, smoking, stress, and age (risk increases after 40). Conditions like diabetes and kidney disease also raise your risk." },
      { heading: "Prevention & Lifestyle Changes", body: "You can significantly reduce your risk by maintaining a healthy weight, exercising regularly (at least 30 minutes most days), reducing salt intake, eating more fruits and vegetables, limiting alcohol, quitting smoking, and managing stress. Regular blood pressure checks are essential — especially if you have risk factors." },
      { heading: "When to See a Doctor", body: "Visit Ggwaatiro Hospital if your blood pressure reading is consistently above 130/80 mmHg, or if you experience any of the symptoms mentioned above. Our HN/DM clinic provides ongoing monitoring and management for patients with hypertension and diabetes." },
    ],
    keyPoints: ["Check your blood pressure regularly", "Reduce salt in your diet", "Exercise at least 30 minutes daily", "Avoid smoking and excessive alcohol", "Visit our HN/DM clinic for ongoing support"],
  },
  {
    id: 2, cat: "maternity", catLabel: "Maternity",
    title: "What to Expect During Antenatal Care at Ggwaatiro Hospital",
    excerpt: "From your first trimester check-up to safe delivery, our midwives and obstetricians walk you through every stage of your pregnancy journey.",
    author: "Maternity Team", initials: "MT", color: "#2563eb",
    date: "April 5, 2026", readTime: "5 min", trending: true,
    content: [
      { heading: "Why Antenatal Care Matters", body: "Regular antenatal check-ups are one of the most important things you can do for yourself and your baby. They allow our team to monitor your health and your baby's development, identify any complications early, and prepare you for a safe delivery." },
      { heading: "Your First Visit", body: "Your first antenatal visit should ideally happen before 12 weeks of pregnancy. At this visit, we will confirm your pregnancy, calculate your due date, take a full medical history, check your blood pressure and weight, and order initial blood tests including HIV, syphilis, blood group, and haemoglobin levels." },
      { heading: "Subsequent Visits", body: "We recommend visits at 16, 24, 28, 32, 36, and 38 weeks. Each visit includes blood pressure monitoring, urine testing, foetal heartbeat check, and measurement of your bump. Ultrasound scans are offered at key stages to check your baby's growth and position." },
      { heading: "Preparing for Delivery", body: "As you approach your due date, our team will discuss your birth plan, signs of labour, when to come to hospital, and what to bring. We have experienced midwives and obstetricians available around the clock for safe deliveries." },
      { heading: "Postnatal Care", body: "After delivery, we provide postnatal check-ups for both mother and baby, breastfeeding support, newborn immunizations, and family planning counselling. Your wellbeing after birth is just as important to us as your care during pregnancy." },
    ],
    keyPoints: ["Start antenatal care before 12 weeks", "Attend all scheduled check-ups", "Ultrasound scans available on-site", "24/7 midwife and obstetrician support", "Postnatal care included"],
  },
  {
    id: 3, cat: "preventive", catLabel: "Preventive Care",
    title: "Why Immunization Matters: Protecting Your Child from Preventable Diseases",
    excerpt: "Vaccines save lives. Our team explains the national immunization schedule, what each vaccine protects against, and why keeping up to date is critical.",
    author: "Paediatrics Team", initials: "PT", color: "#1d4ed8",
    date: "March 28, 2026", readTime: "4 min", trending: false,
    content: [
      { heading: "The Power of Vaccines", body: "Immunization is one of the most cost-effective public health interventions ever developed. Vaccines have eliminated smallpox, nearly eradicated polio, and dramatically reduced deaths from measles, whooping cough, and other diseases that once killed millions of children every year." },
      { heading: "Uganda's National Immunization Schedule", body: "In Uganda, children should receive vaccines at birth (BCG, OPV0, Hepatitis B), at 6 weeks (DPT-HepB-Hib, OPV1, PCV1, Rotavirus1), at 10 weeks (DPT-HepB-Hib, OPV2, PCV2, Rotavirus2), at 14 weeks (DPT-HepB-Hib, OPV3, PCV3, IPV), and at 9 months (Measles-Rubella, Yellow Fever, Vitamin A)." },
      { heading: "Common Concerns Addressed", body: "Some parents worry that vaccines cause autism or overload the immune system. These concerns are not supported by scientific evidence. Vaccines are rigorously tested for safety and effectiveness before approval. The risks of the diseases they prevent far outweigh any minor side effects." },
      { heading: "What to Do If Your Child Missed Vaccines", body: "It is never too late to catch up. Bring your child's immunization card to Ggwaatiro Hospital and our paediatrics team will assess which vaccines are needed and create a catch-up schedule. Do not wait — every day without protection is a risk." },
    ],
    keyPoints: ["Follow the national immunization schedule", "Vaccines are safe and effective", "Catch-up vaccines available at our clinic", "Bring your child's immunization card", "Protect your community through herd immunity"],
  },
  {
    id: 4, cat: "health", catLabel: "Health Tips",
    title: "Diabetes Management: Living Well with HN/DM in Uganda",
    excerpt: "Our HN/DM clinic provides ongoing support for patients managing hypertension and diabetes. Here is what you need to know about monitoring, diet, and medication.",
    author: "Dr. Katumba Joseph", initials: "KJ", color: "#1a3fa8",
    date: "March 20, 2026", readTime: "7 min", trending: false,
    content: [
      { heading: "Understanding Diabetes in Uganda", body: "Diabetes is a growing health challenge in Uganda, with Type 2 diabetes increasingly common due to changing diets and lifestyles. It occurs when the body cannot properly use insulin, leading to high blood sugar levels that damage organs over time if uncontrolled." },
      { heading: "Monitoring Your Blood Sugar", body: "Regular blood sugar monitoring is essential. Fasting blood glucose should ideally be between 4–7 mmol/L. Our laboratory offers HbA1c tests, which show your average blood sugar over the past 3 months — a key indicator of how well your diabetes is controlled." },
      { heading: "Diet and Nutrition", body: "A diabetes-friendly diet focuses on whole grains, vegetables, lean proteins, and healthy fats while limiting sugar, refined carbohydrates, and processed foods. Eating regular meals at consistent times helps stabilise blood sugar. Our team can refer you to a nutritionist for personalised guidance." },
      { heading: "Medication and Insulin", body: "Many patients with Type 2 diabetes can manage their condition with lifestyle changes and oral medication. Some require insulin injections. Never stop or change your medication without consulting your doctor. Our HN/DM clinic ensures you always have access to the right treatment." },
      { heading: "Preventing Complications", body: "Uncontrolled diabetes can lead to blindness, kidney failure, nerve damage, and amputations. Regular check-ups, eye examinations, foot care, and kidney function tests are essential. Our clinic provides comprehensive monitoring to catch complications early." },
    ],
    keyPoints: ["Monitor blood sugar regularly", "Follow a balanced, low-sugar diet", "Take medication as prescribed", "Attend regular HN/DM clinic check-ups", "Check your feet and eyes regularly"],
  },
  {
    id: 5, cat: "wellness", catLabel: "Wellness",
    title: "The Importance of Regular Health Screenings After Age 40",
    excerpt: "Many serious conditions — including cancer, diabetes, and heart disease — can be caught early with routine screenings. Find out which tests you should be getting.",
    author: "General Medicine Team", initials: "GM", color: "#1535a0",
    date: "March 12, 2026", readTime: "5 min", trending: true,
    content: [
      { heading: "Why Screening Matters", body: "Many serious diseases develop silently for years before causing symptoms. By the time symptoms appear, the condition may be advanced and harder to treat. Regular screenings catch problems early — when treatment is most effective, least invasive, and most likely to result in a full recovery." },
      { heading: "Essential Screenings for Adults Over 40", body: "Key tests include: blood pressure (annually), blood sugar and HbA1c (every 1–2 years), cholesterol panel (every 3–5 years), HIV test (at least once, more if at risk), cervical cancer screening for women (every 3 years), breast examination, prostate check for men, eye examination, and dental check-up." },
      { heading: "Know Your Numbers", body: "Understanding your results empowers you to take action. Normal blood pressure is below 120/80 mmHg. Fasting blood sugar should be below 5.6 mmol/L. Total cholesterol should be below 5.2 mmol/L. If your numbers are outside the normal range, our doctors will work with you on a management plan." },
      { heading: "Book Your Screening at Ggwaatiro Hospital", body: "Our laboratory and outpatient department offer comprehensive health screening packages. Walk in any time or call +256 772 428 467 to schedule your check-up. Early detection saves lives — do not wait for symptoms to appear." },
    ],
    keyPoints: ["Screen annually for blood pressure and blood sugar", "Cholesterol check every 3–5 years", "Cervical and breast screening for women", "Prostate check for men over 50", "Early detection dramatically improves outcomes"],
  },
  {
    id: 6, cat: "maternity", catLabel: "Maternity",
    title: "Family Planning Services: Your Options Explained",
    excerpt: "Ggwaatiro Hospital offers a full range of family planning services. Our team explains the available methods, how they work, and how to choose what is right for you.",
    author: "Maternity Team", initials: "MT", color: "#2563eb",
    date: "March 5, 2026", readTime: "5 min", trending: false,
    content: [
      { heading: "Why Family Planning Matters", body: "Family planning allows individuals and couples to decide if, when, and how many children to have. It improves maternal and child health, reduces poverty, and empowers women. Access to family planning is a fundamental health right." },
      { heading: "Short-Term Methods", body: "Short-term methods include condoms (male and female), oral contraceptive pills, and emergency contraception. These are reversible and suitable for those who may want children in the near future. Our team will explain correct usage and effectiveness rates." },
      { heading: "Long-Acting Reversible Methods", body: "Long-acting methods include the injectable (Depo-Provera, given every 3 months), implants (inserted under the skin, effective for 3–5 years), and intrauterine devices (IUDs, effective for 5–10 years). These are highly effective and fully reversible." },
      { heading: "Permanent Methods", body: "For those who are certain they do not want more children, permanent methods include tubal ligation for women and vasectomy for men. These are surgical procedures performed at our hospital." },
      { heading: "Choosing the Right Method", body: "The best method depends on your health, lifestyle, relationship, and future plans. Our family planning counsellors will discuss all options with you confidentially and help you make an informed choice. There is no judgement — only support." },
    ],
    keyPoints: ["Multiple methods available to suit your needs", "All consultations are confidential", "Long-acting methods are highly effective", "Reversible options available", "Walk in or call to book a consultation"],
  },
  {
    id: 7, cat: "preventive", catLabel: "Preventive Care",
    title: "Malaria Prevention in Bweyogerere: What Every Family Should Know",
    excerpt: "Malaria remains a major health concern in our community. Our doctors share practical prevention strategies, early symptoms to watch for, and when to seek treatment.",
    author: "General Medicine Team", initials: "GM", color: "#1535a0",
    date: "Feb 25, 2026", readTime: "4 min", trending: false,
    content: [
      { heading: "Malaria in Our Community", body: "Malaria is caused by Plasmodium parasites transmitted through the bites of infected female Anopheles mosquitoes. In Bweyogerere and the wider Kira area, malaria transmission is year-round, with peaks during and after rainy seasons. It remains one of the most common reasons patients visit our outpatient department." },
      { heading: "Prevention Strategies", body: "The most effective prevention measures include sleeping under an insecticide-treated mosquito net (ITN) every night, using mosquito repellent on exposed skin, wearing long-sleeved clothing in the evenings, eliminating standing water around your home where mosquitoes breed, and keeping windows and doors screened." },
      { heading: "Recognising the Symptoms", body: "Malaria symptoms typically appear 7–14 days after a mosquito bite. They include fever (often with chills and sweating), headache, muscle aches, fatigue, nausea, and vomiting. In severe cases, especially in young children, malaria can cause convulsions, difficulty breathing, and loss of consciousness — seek emergency care immediately." },
      { heading: "Testing and Treatment", body: "Do not self-medicate. Come to Ggwaatiro Hospital for a rapid diagnostic test (RDT) or blood smear. Treatment depends on the type of malaria and its severity. Artemisinin-based combination therapy (ACT) is the standard first-line treatment. Early treatment prevents complications and reduces transmission." },
    ],
    keyPoints: ["Sleep under an insecticide-treated net every night", "Eliminate standing water near your home", "Seek testing at the first sign of fever", "Do not self-medicate — get tested first", "Early treatment prevents serious complications"],
  },
  {
    id: 8, cat: "wellness", catLabel: "Wellness",
    title: "Physiotherapy After Surgery: Why Rehabilitation Matters",
    excerpt: "Post-surgical rehabilitation is key to a full recovery. Our physiotherapy team explains what to expect, how long recovery takes, and how to get the best outcomes.",
    author: "Physiotherapy Team", initials: "PH", color: "#1d4ed8",
    date: "Feb 18, 2026", readTime: "6 min", trending: false,
    content: [
      { heading: "What is Post-Surgical Physiotherapy?", body: "Physiotherapy after surgery is a structured programme of exercises and treatments designed to restore strength, mobility, and function. It reduces pain, prevents complications like blood clots and muscle wasting, and helps you return to normal activities as quickly and safely as possible." },
      { heading: "When Does Rehabilitation Begin?", body: "In many cases, physiotherapy begins within 24–48 hours of surgery — even while you are still in hospital. Early mobilisation is proven to reduce complications and speed recovery. Your physiotherapist will assess your condition and design a programme appropriate for your surgery and fitness level." },
      { heading: "What to Expect", body: "Your rehabilitation programme will typically include breathing exercises (especially after chest or abdominal surgery), gentle range-of-motion exercises, progressive strengthening, balance and coordination training, and guidance on safe return to daily activities. Sessions are tailored to your progress." },
      { heading: "Common Surgeries Requiring Physiotherapy", body: "Physiotherapy is particularly important after orthopaedic surgery (hip and knee replacements, fracture repair), abdominal surgery, cardiac surgery, stroke, and spinal procedures. Our team works closely with our surgeons to ensure a seamless transition from theatre to rehabilitation." },
      { heading: "Tips for a Successful Recovery", body: "Attend all your physiotherapy sessions, follow your home exercise programme, communicate any pain or concerns to your therapist, maintain good nutrition to support healing, and be patient — recovery takes time. Rushing back to activity too soon can cause setbacks." },
    ],
    keyPoints: ["Start physiotherapy as early as your surgeon advises", "Attend all scheduled sessions", "Follow your home exercise programme", "Good nutrition supports healing", "Communicate pain and concerns to your therapist"],
  },
  {
    id: 9, cat: "health", catLabel: "Health Tips",
    title: "Eye Health: Common Conditions We Treat at Our Eye Clinic",
    excerpt: "From cataracts to refractive errors, our eye specialists see a wide range of conditions. Learn about the most common eye problems and how we treat them.",
    author: "Eye Specialist Team", initials: "ES", color: "#1a3fa8",
    date: "Feb 10, 2026", readTime: "5 min", trending: false,
    content: [
      { heading: "The Importance of Eye Health", body: "Good vision is essential for quality of life, learning, and work. Yet many eye conditions develop gradually and painlessly, meaning people often do not seek help until significant damage has occurred. Regular eye examinations are the best way to protect your sight." },
      { heading: "Refractive Errors", body: "Refractive errors — including short-sightedness (myopia), long-sightedness (hyperopia), and astigmatism — are the most common eye conditions. They cause blurred vision and are easily corrected with glasses or contact lenses. Our eye specialists perform comprehensive vision assessments and prescribe corrective lenses." },
      { heading: "Cataracts", body: "A cataract is a clouding of the eye's natural lens, causing blurred or dim vision. It is the leading cause of blindness in Uganda. Cataracts develop slowly with age but can also be caused by diabetes, injury, or prolonged sun exposure. Surgical removal is safe, effective, and restores clear vision." },
      { heading: "Glaucoma", body: "Glaucoma is a group of conditions that damage the optic nerve, often due to increased pressure in the eye. It progresses silently and can cause permanent blindness if untreated. Early detection through regular eye pressure checks is critical. Treatment includes eye drops, laser therapy, or surgery." },
      { heading: "When to Visit Our Eye Clinic", body: "See our eye specialists if you experience blurred or double vision, eye pain or redness, sudden vision loss, seeing halos around lights, or if you have diabetes or a family history of glaucoma. Children should have their eyes checked before starting school." },
    ],
    keyPoints: ["Have your eyes checked regularly", "Refractive errors are easily corrected with glasses", "Cataracts are treatable with surgery", "Glaucoma can be managed if caught early", "Diabetics should have annual eye examinations"],
  },
];
