

export interface Movie {
  id: number
  title: string
  image: string
  poster: string
  trailerPoster: string
  rating: number
  year: number
  genre: string
  vj?: string
  views: string
  size: string
  length: string
  description: string
  director: string
  cast: string[]
  trailerUrl: string
  videoUrl: string
}

export const moviesData: Movie[] = [
  {
    id: 1,
    title: "Quantum Horizon",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.9,
    year: 2024,
    genre: "Sci-Fi",
    vj: "VJ Junior",
    views: "2.5M",
    size: "2.1 GB",
    length: "2h 15m",
    description:
      "In a future where quantum technology has unlocked parallel dimensions, a brilliant physicist discovers a way to communicate across realities. But when a catastrophic experiment threatens to collapse all dimensions into one, she must race against time to prevent the end of existence itself.",
    director: "Sarah Chen",
    cast: ["Emma Stone", "Oscar Isaac", "Tilda Swinton", "John Boyega"],
    trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 2,
    title: "The Last Symphony",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 9.2,
    year: 2024,
    genre: "Drama",
    views: "3.8M",
    size: "1.8 GB",
    length: "2h 32m",
    description:
      "A legendary conductor returns to the stage for one final performance after a decade of silence. As the orchestra prepares for the concert of a lifetime, secrets from the past threaten to unravel everything they've worked for.",
    director: "Michael Anderson",
    cast: ["Cate Blanchett", "Ralph Fiennes", "Saoirse Ronan", "Benedict Cumberbatch"],
        trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 3,
    title: "Shadow Protocol",
   image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.5,
    year: 2024,
    genre: "Action",
    vj: "VJ Emmy",
    views: "4.2M",
    size: "2.5 GB",
    length: "2h 8m",
    description:
      "A former black ops agent is pulled back into the world of espionage when a rogue AI threatens global security. With time running out, he must assemble a team of specialists to infiltrate the most secure facility on Earth.",
    director: "James Cameron",
    cast: ["Tom Hardy", "Charlize Theron", "Idris Elba", "Rebecca Ferguson"],
        trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 4,
    title: "Midnight in Tokyo",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.7,
    year: 2023,
    genre: "Thriller",
    vj: "VJ Ice P",
    views: "1.9M",
    size: "1.6 GB",
    length: "1h 58m",
    description:
      "A detective investigating a series of mysterious disappearances in Tokyo's underground nightlife discovers a conspiracy that reaches the highest levels of power. As he gets closer to the truth, he becomes the next target.",
    director: "Park Chan-wook",
    cast: ["Ken Watanabe", "Rinko Kikuchi", "Tadanobu Asano", "Takeshi Kitano"],
        trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 5,
    title: "The Architect",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.3,
    year: 2023,
    genre: "Thriller",
    views: "2.1M",
    size: "1.9 GB",
    length: "2h 5m",
    description:
      "A renowned architect begins to question reality when the buildings he designs start appearing in his dreams before construction begins. As the line between imagination and reality blurs, he must uncover the truth before losing his mind.",
    director: "Denis Villeneuve",
    cast: ["Jake Gyllenhaal", "Amy Adams", "Michael Shannon", "Laura Linney"],
        trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 6,
    title: "Steel Thunder",
   image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.1,
    year: 2024,
    genre: "Action",
    vj: "VJ Mark",
    views: "3.5M",
    size: "2.3 GB",
    length: "2h 12m",
    description:
      "When a military convoy carrying experimental weapons is hijacked, an elite special forces team must track down the terrorists before they can unleash devastation on major cities around the world.",
    director: "Michael Bay",
    cast: ["Chris Hemsworth", "Gal Gadot", "Jason Statham", "Michelle Rodriguez"],
    trailerUrl: "/EENIE MEANIE JR 2025.mkv",
    videoUrl: "/EENIE MEANIE JR 2025.mkv",
  },
  {
    id: 7,
    title: "Velocity",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 7.9,
    year: 2023,
    genre: "Action",
    vj: "VJ Junior",
    views: "2.8M",
    size: "2.0 GB",
    length: "1h 55m",
    description:
      "A street racer is forced to work undercover for the FBI to infiltrate an international crime syndicate that uses illegal racing circuits to transport stolen goods across borders.",
    director: "Justin Lin",
    cast: ["Vin Diesel", "Michelle Rodriguez", "Sung Kang", "Nathalie Emmanuel"],
    trailerUrl: "/videos/velocity-trailer.mp4",
    videoUrl: "/videos/velocity-full.mp4",
  },
  {
    id: 8,
    title: "Phoenix Rising",
   image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 8.4,
    year: 2024,
    genre: "Action",
    views: "3.1M",
    size: "2.2 GB",
    length: "2h 18m",
    description:
      "After a devastating attack destroys his city, a firefighter with a mysterious past must embrace his hidden abilities to save survivors and confront the forces responsible for the destruction.",
    director: "Zack Snyder",
    cast: ["Henry Cavill", "Margot Robbie", "Dwayne Johnson", "Zendaya"],
    trailerUrl: "/videos/phoenix-rising-trailer.mp4",
    videoUrl: "/videos/phoenix-rising-full.mp4",
  },
  {
    id: 9,
    title: "Code Red",
    image: "/action-movie-poster-military-code-red.jpg",
    poster: "/posters/code-red-poster.jpg",
    trailerPoster: "/posters/code-red-trailer-thumb.jpg",
    rating: 8.0,
    year: 2023,
    genre: "Action",
    vj: "VJ Emmy",
    views: "2.6M",
    size: "2.1 GB",
    length: "2h 3m",
    description:
      "A military base goes into lockdown when a deadly virus is accidentally released. A team of soldiers must contain the outbreak while fighting off infected personnel and uncovering the truth behind the virus's origin.",
    director: "Kathryn Bigelow",
    cast: ["Jeremy Renner", "Jessica Chastain", "Anthony Mackie", "Brian Geraghty"],
    trailerUrl: "/videos/code-red-trailer.mp4",
    videoUrl: "/videos/code-red-full.mp4",
  },
  {
    id: 10,
    title: "Titan Force",
    image: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    poster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    trailerPoster: "/8fdeb8f8cc9b17c0c17cb6c5ae0fd35c.jpg",
    rating: 7.8,
    year: 2022,
    genre: "Action",
    views: "1.7M",
    size: "1.9 GB",
    length: "1h 52m",
    description:
      "An elite military unit is sent on a covert mission to rescue hostages from a heavily fortified compound. But when their extraction plan fails, they must fight their way out against overwhelming odds.",
    director: "Antoine Fuqua",
    cast: ["Denzel Washington", "Mark Wahlberg", "Pedro Pascal", "Lupita Nyong'o"],
    trailerUrl: "/videos/titan-force-trailer.mp4",
    videoUrl: "/videos/titan-force-full.mp4",
  },
  {
    id: 11,
    title: "Echoes of Tomorrow",
    image: "/drama-movie-poster-emotional-family-story.jpg",
    poster: "/posters/echoes-tomorrow-poster.jpg",
    trailerPoster: "/posters/echoes-tomorrow-trailer-thumb.jpg",
    rating: 9.0,
    year: 2024,
    genre: "Drama",
    vj: "VJ Ice P",
    views: "2.9M",
    size: "1.7 GB",
    length: "2h 25m",
    description:
      "Three generations of a family come together for a reunion that forces them to confront long-buried secrets and heal old wounds. A powerful story about forgiveness, love, and the ties that bind us.",
    director: "Greta Gerwig",
    cast: ["Meryl Streep", "Timothée Chalamet", "Florence Pugh", "Laura Dern"],
    trailerUrl: "/videos/echoes-tomorrow-trailer.mp4",
    videoUrl: "/videos/echoes-tomorrow-full.mp4",
  },
  {
    id: 12,
    title: "The Painter's Dream",
    image: "/drama-movie-poster-artist-painter-canvas.jpg",
    poster: "/posters/painters-dream-poster.jpg",
    trailerPoster: "/posters/painters-dream-trailer-thumb.jpg",
    rating: 8.8,
    year: 2023,
    genre: "Drama",
    views: "1.5M",
    size: "1.6 GB",
    length: "2h 10m",
    description:
      "An aging painter struggles to complete his final masterpiece while battling dementia. As his memories fade, his art becomes the only way to hold onto the life and love he's known.",
    director: "Paolo Sorrentino",
    cast: ["Anthony Hopkins", "Olivia Colman", "Mark Rylance", "Emily Watson"],
    trailerUrl: "/videos/painters-dream-trailer.mp4",
    videoUrl: "/videos/painters-dream-full.mp4",
  },
]

